before:
  hooks:
    - go mod download
builds:
  - main: kubectl-karbon.go
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/nutanix/kubectl-karbon/version.Version={{.Version}}
      - -X github.com/nutanix/kubectl-karbon/version.Commit={{.ShortCommit}}
      - -X github.com/nutanix/kubectl-karbon/version.Date={{.Date}}
      - -X github.com/nutanix/kubectl-karbon/version.BuiltBy=GoReleaser
      - -X github.com/nutanix/kubectl-karbon/version.OsName={{.Os}}
      - -X github.com/nutanix/kubectl-karbon/version.PlatformName={{.Arch}}
archives:
  - builds:
      - kubectl-karbon
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: false
    format: tar.gz

# Homebrew
brews:
  - name: kubectl-karbon
    repository:
      owner: nutanix
      name: homebrew-tap
      branch: main
      token: "{{ .Env.NUTANIX_BOT_PAT }}"
    commit_author:
      name: tuxtof
      email: christophe.jauffret@nutanix.com
    directory: Formula
    homepage: https://github.com/nutanix/kubectl-karbon
    description: Kubectl extension to quickly connect to an existing karbon cluster!
    test: |
      system "kubectl-karbon version"
