---
name: Release
on:
  push:
    tags:
    - 'v*.*.*'
jobs:
  release_job:
    name: GoReleaser & Krew
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.21'
    - name: GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NUTANIX_BOT_PAT: ${{ secrets.NUTANIX_BOT_PAT }}
    - name: Update new version in krew-index
      uses: rajatjindal/krew-release-bot@v0.0.46